plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'work'
version = '0.0.1-SNAPSHOT'
description = 'tradeWebService'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	//Spring starter
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
 	implementation 'org.springframework.boot:spring-boot-starter-validation'

	//Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	//Mapstruct
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	//Lombok-MapStruct Binding
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	//flyway
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-mysql'

	//Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'

	//JWT Token
	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	runtimeOnly 'com.mysql:mysql-connector-j'

	//Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'io.lettuce:lettuce-core'

	//Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'

	//QueryDSL
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	//QClass 생성용 Annotation Processor
	annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

	//AWS
	implementation platform('software.amazon.awssdk:bom:2.31.67')
	implementation 'software.amazon.awssdk:s3'

	//Actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	//-----------test
	//lombok
	testImplementation 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	testImplementation 'org.testcontainers:junit-jupiter:1.21.3'
	testImplementation 'org.testcontainers:mysql:1.20.1'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	//container
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'

	//spring security
	testImplementation 'org.springframework.security:spring-security-test'
}

//QClass 생성 위치 설정
//def querydslDir = "src/main/generated"
//
//sourceSets {
//	main.java.srcDirs += [ querydslDir ]
//}

//tasks.withType(JavaCompile) {
//	options.getGeneratedSourceOutputDirectory().set(file(querydslDir))
//}

//clean {
//	delete file(querydslDir)
//}

tasks.named('test') {
	useJUnitPlatform()
}
