spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

file:
  storage:
    type: s3
  display:
    prefix: "https://${AWS_CLOUDFRONT_DOMAIN}"

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY_ID}

  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}
