spring:
  application:
    name: trade

  messages:
    basename: messages,errors

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/study_trade?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: asdf
    driver-class-name: com.mysql.cj.jdbc.Driver

   redis:
    host: localhost
    port: 6379
    timeout: 2000
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    validate-on-migrate: true

server:
  port: 8081

jwt:
   secret: imsi-secret-key-afwefw-70684-96928592834928349283492834928349283
   expiration: 900000       # 15분 (ms)
   refresh:
     expiration: 604800000    # 7일 (ms)


#logging:
#  level:
#    org.springframework.security: DEBUG