spring:
  application:
    name: trade

  messages:
    basename: messages,errors

  profiles:
    active: local

  # Redis 공통 옵션
  data:
    redis:
      timeout: 2000
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    validate-on-migrate: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:imsi-secret-key-afwefw-70684-96928592834928349283492834928349283}
  expiration: 900000
  refresh:
    expiration: 604800000

file:
  storage:
    type: local
